logging:
  level: "INFO"
  format: "%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d %(funcName)s()] %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"

transfer:
  timeout_seconds: 120

bigquery:
  ignore_unknown_values: true